# Starts the SpeedTest using IRIS. 
#
# This will use standard IRIS to run the speed test. If you are a customer, you can
# pull it form the Docker Store with your DockerHub username and password. If you are an
# InterSystems employee

version: '3.7'

services:
  htapui:
    depends_on:
      - htapmaster
    container_name: htapui
    hostname: htapui
    image: intersystemsdc/irisdemo-demo-htap:ui-version-2.5.0
    ports:
    - "10000:4200" # Where Node Will be listening

  htapirisdb: 
    # We can't use clean IRIS because its HEALTHCHECK period is too long.
    # So the downloadiris.sh script builds a new image that fixes the HEALTHCHECK
    # and pushes it to our private repository so we can pull it here.
    image: intersystems/iris:2020.1.0.215.0
    hostname: htapirisdb
    command: --key /irislicense/iris.key
    init: true
    container_name: htapirisdb
    ports:
    - "10001:52773" # 52773 is the webserver/management portal port: http://localhost:10001/csp/sys/UtilHome.csp
    volumes:
    - type: bind
      source: ./IRISLicense/
      target: /irislicense


  htapmaster:
    depends_on: 
      - htapirisdb
    container_name: htapmaster
    hostname: htapmaster
    init: true
    image: intersystemsdc/irisdemo-demo-htap:master-version-2.5.0
    ports:
      - "10002:8080" # Where Springboot Will be listening
    environment:
      - MASTER_SPEEDTEST_TITLE=SpeedTest | IRIS 2020.1.0.215.0
      - START_CONSUMERS=true
      - DISABLE_JOURNAL_FOR_DROP_TABLE=true
      - DISABLE_JOURNAL_FOR_TRUNCATE_TABLE=true
      - INGESTION_THREADS_PER_WORKER=2
      - INGESTION_BATCH_SIZE=1000
      - INGESTION_JDBC_URL=jdbc:IRIS://htapirisdb:51773/USER
      - INGESTION_JDBC_USERNAME=SuperUser
      - INGESTION_JDBC_PASSWORD=sys
      - CONSUMER_JDBC_URL=jdbc:IRIS://htapirisdb:51773/USER
      - CONSUMER_JDBC_USERNAME=SuperUser
      - CONSUMER_JDBC_PASSWORD=sys
      - CONSUMER_THREADS_PER_WORKER=1
      - CONSUMER_TIME_BETWEEN_QUERIES_IN_MILLIS=0

  ingest-worker1:
    depends_on: 
      - htapmaster
    container_name: ingest-worker1
    hostname: ingest-worker1
    init: true
    image: intersystemsdc/irisdemo-demo-htap:iris-jdbc-ingest-worker-version-2.5.0
    ports:
      - "10003:8080" # Where Springboot Will be listening
    environment:
      - MASTER_HOSTNAME=htapmaster
      - MASTER_PORT=8080

  query-worker1:
    depends_on: 
      - htapmaster
    container_name: query-worker1
    hostname: query-worker1
    init: true
    image: intersystemsdc/irisdemo-demo-htap:iris-jdbc-query-worker-version-2.5.0
    ports:
      - "10004:8080" # Where Springboot Will be listening
    environment:
      - MASTER_HOSTNAME=htapmaster
      - MASTER_PORT=8080
